### ISSUE TITLE
Links for inactive media entries are hardcoded to anime

### ISSUE THREAD

**Issue by Siebrenvde** [TehNut/fern#1]
The links for inactive media entries are hardcoded to `https://anilist.co/anime/...`, leading to a 404 when clicking on a manga entry.

https://github.com/TehNut/fern/blob/d126eacdf3362e9beba053bade847dba501e4433/src/routes/inactive/_components/MediaView.svelte#L34

**Comment by TehNut** [comment]
oop

**Comment by TehNut** [comment]
Should be good, now. Thanks for the report!
